#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Albrus
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Albrus")]
	public partial class DataProjectListDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDashBoardTask(DashBoardTask instance);
    partial void UpdateDashBoardTask(DashBoardTask instance);
    partial void DeleteDashBoardTask(DashBoardTask instance);
    partial void InsertExersiceTask(ExersiceTask instance);
    partial void UpdateExersiceTask(ExersiceTask instance);
    partial void DeleteExersiceTask(ExersiceTask instance);
    partial void InsertProjectList(ProjectList instance);
    partial void UpdateProjectList(ProjectList instance);
    partial void DeleteProjectList(ProjectList instance);
    partial void InsertTaskProject(TaskProject instance);
    partial void UpdateTaskProject(TaskProject instance);
    partial void DeleteTaskProject(TaskProject instance);
    #endregion
		
		public DataProjectListDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AlbrusConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataProjectListDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataProjectListDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataProjectListDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataProjectListDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DashBoardTask> DashBoardTasks
		{
			get
			{
				return this.GetTable<DashBoardTask>();
			}
		}
		
		public System.Data.Linq.Table<ExersiceTask> ExersiceTasks
		{
			get
			{
				return this.GetTable<ExersiceTask>();
			}
		}
		
		public System.Data.Linq.Table<ProjectList> ProjectLists
		{
			get
			{
				return this.GetTable<ProjectList>();
			}
		}
		
		public System.Data.Linq.Table<TaskProject> TaskProjects
		{
			get
			{
				return this.GetTable<TaskProject>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DashBoardTask")]
	public partial class DashBoardTask : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDash;
		
		private System.Nullable<int> _idProj;
		
		private string _name;
		
		private string _information;
		
		private System.Nullable<System.DateTime> _dataCreate;
		
		private System.Nullable<int> _position;
		
		private System.Nullable<int> _authorId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDashChanging(int value);
    partial void OnidDashChanged();
    partial void OnidProjChanging(System.Nullable<int> value);
    partial void OnidProjChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OninformationChanging(string value);
    partial void OninformationChanged();
    partial void OndataCreateChanging(System.Nullable<System.DateTime> value);
    partial void OndataCreateChanged();
    partial void OnpositionChanging(System.Nullable<int> value);
    partial void OnpositionChanged();
    partial void OnauthorIdChanging(System.Nullable<int> value);
    partial void OnauthorIdChanged();
    #endregion
		
		public DashBoardTask()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDash", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDash
		{
			get
			{
				return this._idDash;
			}
			set
			{
				if ((this._idDash != value))
				{
					this.OnidDashChanging(value);
					this.SendPropertyChanging();
					this._idDash = value;
					this.SendPropertyChanged("idDash");
					this.OnidDashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProj", DbType="Int")]
		public System.Nullable<int> idProj
		{
			get
			{
				return this._idProj;
			}
			set
			{
				if ((this._idProj != value))
				{
					this.OnidProjChanging(value);
					this.SendPropertyChanging();
					this._idProj = value;
					this.SendPropertyChanged("idProj");
					this.OnidProjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_information", DbType="NChar(200)")]
		public string information
		{
			get
			{
				return this._information;
			}
			set
			{
				if ((this._information != value))
				{
					this.OninformationChanging(value);
					this.SendPropertyChanging();
					this._information = value;
					this.SendPropertyChanged("information");
					this.OninformationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCreate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataCreate
		{
			get
			{
				return this._dataCreate;
			}
			set
			{
				if ((this._dataCreate != value))
				{
					this.OndataCreateChanging(value);
					this.SendPropertyChanging();
					this._dataCreate = value;
					this.SendPropertyChanged("dataCreate");
					this.OndataCreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="Int")]
		public System.Nullable<int> position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_authorId", DbType="Int")]
		public System.Nullable<int> authorId
		{
			get
			{
				return this._authorId;
			}
			set
			{
				if ((this._authorId != value))
				{
					this.OnauthorIdChanging(value);
					this.SendPropertyChanging();
					this._authorId = value;
					this.SendPropertyChanged("authorId");
					this.OnauthorIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExersiceTask")]
	public partial class ExersiceTask : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idExer;
		
		private System.Nullable<int> _idTask;
		
		private string _description;
		
		private System.Nullable<int> _status;
		
		private System.Nullable<System.DateTime> _dataStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidExerChanging(int value);
    partial void OnidExerChanged();
    partial void OnidTaskChanging(System.Nullable<int> value);
    partial void OnidTaskChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OndataStatusChanging(System.Nullable<System.DateTime> value);
    partial void OndataStatusChanged();
    #endregion
		
		public ExersiceTask()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idExer", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idExer
		{
			get
			{
				return this._idExer;
			}
			set
			{
				if ((this._idExer != value))
				{
					this.OnidExerChanging(value);
					this.SendPropertyChanging();
					this._idExer = value;
					this.SendPropertyChanged("idExer");
					this.OnidExerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTask", DbType="Int")]
		public System.Nullable<int> idTask
		{
			get
			{
				return this._idTask;
			}
			set
			{
				if ((this._idTask != value))
				{
					this.OnidTaskChanging(value);
					this.SendPropertyChanging();
					this._idTask = value;
					this.SendPropertyChanged("idTask");
					this.OnidTaskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NChar(200)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataStatus", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataStatus
		{
			get
			{
				return this._dataStatus;
			}
			set
			{
				if ((this._dataStatus != value))
				{
					this.OndataStatusChanging(value);
					this.SendPropertyChanging();
					this._dataStatus = value;
					this.SendPropertyChanged("dataStatus");
					this.OndataStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProjectList")]
	public partial class ProjectList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idProj;
		
		private string _name;
		
		private string _information;
		
		private System.Nullable<System.DateTime> _dataCreate;
		
		private System.Nullable<System.DateTime> _dataStart;
		
		private System.Nullable<System.DateTime> _dataEnd;
		
		private System.Nullable<int> _visible;
		
		private System.Nullable<int> _authorId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidProjChanging(int value);
    partial void OnidProjChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OninformationChanging(string value);
    partial void OninformationChanged();
    partial void OndataCreateChanging(System.Nullable<System.DateTime> value);
    partial void OndataCreateChanged();
    partial void OndataStartChanging(System.Nullable<System.DateTime> value);
    partial void OndataStartChanged();
    partial void OndataEndChanging(System.Nullable<System.DateTime> value);
    partial void OndataEndChanged();
    partial void OnvisibleChanging(System.Nullable<int> value);
    partial void OnvisibleChanged();
    partial void OnauthorIdChanging(System.Nullable<int> value);
    partial void OnauthorIdChanged();
    #endregion
		
		public ProjectList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idProj", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idProj
		{
			get
			{
				return this._idProj;
			}
			set
			{
				if ((this._idProj != value))
				{
					this.OnidProjChanging(value);
					this.SendPropertyChanging();
					this._idProj = value;
					this.SendPropertyChanged("idProj");
					this.OnidProjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_information", DbType="NChar(200)")]
		public string information
		{
			get
			{
				return this._information;
			}
			set
			{
				if ((this._information != value))
				{
					this.OninformationChanging(value);
					this.SendPropertyChanging();
					this._information = value;
					this.SendPropertyChanged("information");
					this.OninformationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCreate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataCreate
		{
			get
			{
				return this._dataCreate;
			}
			set
			{
				if ((this._dataCreate != value))
				{
					this.OndataCreateChanging(value);
					this.SendPropertyChanging();
					this._dataCreate = value;
					this.SendPropertyChanged("dataCreate");
					this.OndataCreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataStart
		{
			get
			{
				return this._dataStart;
			}
			set
			{
				if ((this._dataStart != value))
				{
					this.OndataStartChanging(value);
					this.SendPropertyChanging();
					this._dataStart = value;
					this.SendPropertyChanged("dataStart");
					this.OndataStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataEnd
		{
			get
			{
				return this._dataEnd;
			}
			set
			{
				if ((this._dataEnd != value))
				{
					this.OndataEndChanging(value);
					this.SendPropertyChanging();
					this._dataEnd = value;
					this.SendPropertyChanged("dataEnd");
					this.OndataEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visible", DbType="Int")]
		public System.Nullable<int> visible
		{
			get
			{
				return this._visible;
			}
			set
			{
				if ((this._visible != value))
				{
					this.OnvisibleChanging(value);
					this.SendPropertyChanging();
					this._visible = value;
					this.SendPropertyChanged("visible");
					this.OnvisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_authorId", DbType="Int")]
		public System.Nullable<int> authorId
		{
			get
			{
				return this._authorId;
			}
			set
			{
				if ((this._authorId != value))
				{
					this.OnauthorIdChanging(value);
					this.SendPropertyChanging();
					this._authorId = value;
					this.SendPropertyChanged("authorId");
					this.OnauthorIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaskProject")]
	public partial class TaskProject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTask;
		
		private System.Nullable<int> _idDash;
		
		private string _name;
		
		private string _information;
		
		private System.Nullable<int> _position;
		
		private System.Nullable<System.DateTime> _dataCreate;
		
		private System.Nullable<System.DateTime> _dataStart;
		
		private System.Nullable<System.DateTime> _dataEnd;
		
		private System.Nullable<int> _authorId;
		
		private System.Nullable<int> _workerId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTaskChanging(int value);
    partial void OnidTaskChanged();
    partial void OnidDashChanging(System.Nullable<int> value);
    partial void OnidDashChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OninformationChanging(string value);
    partial void OninformationChanged();
    partial void OnpositionChanging(System.Nullable<int> value);
    partial void OnpositionChanged();
    partial void OndataCreateChanging(System.Nullable<System.DateTime> value);
    partial void OndataCreateChanged();
    partial void OndataStartChanging(System.Nullable<System.DateTime> value);
    partial void OndataStartChanged();
    partial void OndataEndChanging(System.Nullable<System.DateTime> value);
    partial void OndataEndChanged();
    partial void OnauthorIdChanging(System.Nullable<int> value);
    partial void OnauthorIdChanged();
    partial void OnworkerIdChanging(System.Nullable<int> value);
    partial void OnworkerIdChanged();
    #endregion
		
		public TaskProject()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTask", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTask
		{
			get
			{
				return this._idTask;
			}
			set
			{
				if ((this._idTask != value))
				{
					this.OnidTaskChanging(value);
					this.SendPropertyChanging();
					this._idTask = value;
					this.SendPropertyChanged("idTask");
					this.OnidTaskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDash", DbType="Int")]
		public System.Nullable<int> idDash
		{
			get
			{
				return this._idDash;
			}
			set
			{
				if ((this._idDash != value))
				{
					this.OnidDashChanging(value);
					this.SendPropertyChanging();
					this._idDash = value;
					this.SendPropertyChanged("idDash");
					this.OnidDashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_information", DbType="NChar(200)")]
		public string information
		{
			get
			{
				return this._information;
			}
			set
			{
				if ((this._information != value))
				{
					this.OninformationChanging(value);
					this.SendPropertyChanging();
					this._information = value;
					this.SendPropertyChanged("information");
					this.OninformationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="Int")]
		public System.Nullable<int> position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCreate", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataCreate
		{
			get
			{
				return this._dataCreate;
			}
			set
			{
				if ((this._dataCreate != value))
				{
					this.OndataCreateChanging(value);
					this.SendPropertyChanging();
					this._dataCreate = value;
					this.SendPropertyChanged("dataCreate");
					this.OndataCreateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataStart
		{
			get
			{
				return this._dataStart;
			}
			set
			{
				if ((this._dataStart != value))
				{
					this.OndataStartChanging(value);
					this.SendPropertyChanging();
					this._dataStart = value;
					this.SendPropertyChanged("dataStart");
					this.OndataStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataEnd", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataEnd
		{
			get
			{
				return this._dataEnd;
			}
			set
			{
				if ((this._dataEnd != value))
				{
					this.OndataEndChanging(value);
					this.SendPropertyChanging();
					this._dataEnd = value;
					this.SendPropertyChanged("dataEnd");
					this.OndataEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_authorId", DbType="Int")]
		public System.Nullable<int> authorId
		{
			get
			{
				return this._authorId;
			}
			set
			{
				if ((this._authorId != value))
				{
					this.OnauthorIdChanging(value);
					this.SendPropertyChanging();
					this._authorId = value;
					this.SendPropertyChanged("authorId");
					this.OnauthorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workerId", DbType="Int")]
		public System.Nullable<int> workerId
		{
			get
			{
				return this._workerId;
			}
			set
			{
				if ((this._workerId != value))
				{
					this.OnworkerIdChanging(value);
					this.SendPropertyChanging();
					this._workerId = value;
					this.SendPropertyChanged("workerId");
					this.OnworkerIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
