<?xml version="1.0" encoding="utf-8"?><Database Name="PriceChecker" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.13.15.72;Initial Catalog=PriceChecker;User ID=test2" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PriceCheckerConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Devices" Member="Devices">
    <Type Name="Device">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ipAdress" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="idDevice" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeviceLogs" Member="DeviceLogs">
    <Type Name="DeviceLog">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ipAdress" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="idDevice" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="dataLog" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="logMessage" Type="System.String" DbType="NChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>